// <auto-generated />
using System;
using CPRG005.Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CPRG005.Final.Data.Migrations
{
    [DbContext(typeof(MarinaDbContext))]
    [Migration("20210524221948_update model data")]
    partial class updatemodeldata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Authorize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Authorizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Password = "10000.z2GCnoFXWCmurPJfIBlFZg==.6m4/OO/bkctGxXSjFJt+fdVRTHvh+LVVb4aVM+WF8zk=",
                            UserName = "jdoe"
                        });
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Boats");
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Phoenix",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "555-545-1212"
                        });
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Dock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasElectricService")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWaterService")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Docks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasElectricService = true,
                            HasWaterService = true,
                            LocationId = 1,
                            Name = "Dock A"
                        },
                        new
                        {
                            Id = 2,
                            HasElectricService = false,
                            HasWaterService = true,
                            LocationId = 1,
                            Name = "Dock B"
                        },
                        new
                        {
                            Id = 3,
                            HasElectricService = false,
                            HasWaterService = false,
                            LocationId = 1,
                            Name = "Dock C"
                        });
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Lease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SlipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LeaseTypeId");

                    b.HasIndex("SlipId");

                    b.ToTable("Leases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            EndDate = new DateTime(2008, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaseTypeId = 4,
                            SlipId = 3,
                            StartDate = new DateTime(2007, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.LeaseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StandardRateAmount")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("LeaseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Daily",
                            StandardRateAmount = 25.50m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weekly",
                            StandardRateAmount = 145.50m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monthly",
                            StandardRateAmount = 500.00m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Yearly",
                            StandardRateAmount = 5000.00m
                        });
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Inland Lake"
                        },
                        new
                        {
                            Id = 2,
                            Name = "San Diego"
                        });
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Slip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DockId")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DockId");

                    b.ToTable("Slips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 2,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 3,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 4,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 5,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 6,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 7,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 8,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 9,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 10,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 11,
                            DockId = 1,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 12,
                            DockId = 1,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 13,
                            DockId = 1,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 14,
                            DockId = 1,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 15,
                            DockId = 1,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 16,
                            DockId = 1,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 17,
                            DockId = 1,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 18,
                            DockId = 1,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 19,
                            DockId = 1,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 20,
                            DockId = 1,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 21,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 22,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 23,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 24,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 25,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 26,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 27,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 28,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 29,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 30,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 31,
                            DockId = 1,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 32,
                            DockId = 1,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 33,
                            DockId = 1,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 34,
                            DockId = 1,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 35,
                            DockId = 1,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 36,
                            DockId = 1,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 37,
                            DockId = 1,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 38,
                            DockId = 1,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 39,
                            DockId = 1,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 40,
                            DockId = 1,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 41,
                            DockId = 1,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 42,
                            DockId = 1,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 43,
                            DockId = 1,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 44,
                            DockId = 1,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 45,
                            DockId = 1,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 46,
                            DockId = 1,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 47,
                            DockId = 1,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 48,
                            DockId = 1,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 49,
                            DockId = 1,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 50,
                            DockId = 1,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 51,
                            DockId = 2,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 52,
                            DockId = 2,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 53,
                            DockId = 2,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 54,
                            DockId = 2,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 55,
                            DockId = 2,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 56,
                            DockId = 2,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 57,
                            DockId = 2,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 58,
                            DockId = 2,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 59,
                            DockId = 2,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 60,
                            DockId = 2,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            Id = 61,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 62,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 63,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 64,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 65,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 66,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 67,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 68,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 69,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 70,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            Id = 71,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 72,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 73,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 74,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 75,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 76,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 77,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 78,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 79,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 80,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            Id = 81,
                            DockId = 2,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 82,
                            DockId = 2,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 83,
                            DockId = 2,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 84,
                            DockId = 2,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 85,
                            DockId = 2,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 86,
                            DockId = 2,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 87,
                            DockId = 2,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 88,
                            DockId = 2,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 89,
                            DockId = 2,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 90,
                            DockId = 2,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 91,
                            DockId = 2,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 92,
                            DockId = 2,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 93,
                            DockId = 2,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 94,
                            DockId = 2,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 95,
                            DockId = 2,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 96,
                            DockId = 2,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 97,
                            DockId = 2,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 98,
                            DockId = 2,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 99,
                            DockId = 2,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 100,
                            DockId = 2,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 101,
                            DockId = 2,
                            Length = 26,
                            Width = 10
                        },
                        new
                        {
                            Id = 102,
                            DockId = 2,
                            Length = 26,
                            Width = 10
                        },
                        new
                        {
                            Id = 103,
                            DockId = 2,
                            Length = 26,
                            Width = 10
                        },
                        new
                        {
                            Id = 104,
                            DockId = 2,
                            Length = 26,
                            Width = 10
                        },
                        new
                        {
                            Id = 105,
                            DockId = 2,
                            Length = 26,
                            Width = 10
                        },
                        new
                        {
                            Id = 106,
                            DockId = 2,
                            Length = 26,
                            Width = 10
                        },
                        new
                        {
                            Id = 107,
                            DockId = 2,
                            Length = 26,
                            Width = 10
                        },
                        new
                        {
                            Id = 108,
                            DockId = 2,
                            Length = 26,
                            Width = 10
                        },
                        new
                        {
                            Id = 109,
                            DockId = 2,
                            Length = 26,
                            Width = 10
                        },
                        new
                        {
                            Id = 110,
                            DockId = 2,
                            Length = 26,
                            Width = 10
                        },
                        new
                        {
                            Id = 111,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 112,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 113,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 114,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 115,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 116,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 117,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 118,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 119,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 120,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            Id = 121,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 122,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 123,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 124,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 125,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 126,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 127,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 128,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 129,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 130,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            Id = 131,
                            DockId = 3,
                            Length = 28,
                            Width = 10
                        },
                        new
                        {
                            Id = 132,
                            DockId = 3,
                            Length = 28,
                            Width = 10
                        },
                        new
                        {
                            Id = 133,
                            DockId = 3,
                            Length = 28,
                            Width = 10
                        },
                        new
                        {
                            Id = 134,
                            DockId = 3,
                            Length = 28,
                            Width = 10
                        },
                        new
                        {
                            Id = 135,
                            DockId = 3,
                            Length = 28,
                            Width = 10
                        },
                        new
                        {
                            Id = 136,
                            DockId = 3,
                            Length = 28,
                            Width = 10
                        },
                        new
                        {
                            Id = 137,
                            DockId = 3,
                            Length = 28,
                            Width = 10
                        },
                        new
                        {
                            Id = 138,
                            DockId = 3,
                            Length = 28,
                            Width = 10
                        },
                        new
                        {
                            Id = 139,
                            DockId = 3,
                            Length = 28,
                            Width = 10
                        },
                        new
                        {
                            Id = 140,
                            DockId = 3,
                            Length = 28,
                            Width = 10
                        });
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Authorize", b =>
                {
                    b.HasOne("CPRG005.Final.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Boat", b =>
                {
                    b.HasOne("CPRG005.Final.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Dock", b =>
                {
                    b.HasOne("CPRG005.Final.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Lease", b =>
                {
                    b.HasOne("CPRG005.Final.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPRG005.Final.Domain.Entities.LeaseType", "LeaseType")
                        .WithMany()
                        .HasForeignKey("LeaseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPRG005.Final.Domain.Entities.Slip", "Slip")
                        .WithMany()
                        .HasForeignKey("SlipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LeaseType");

                    b.Navigation("Slip");
                });

            modelBuilder.Entity("CPRG005.Final.Domain.Entities.Slip", b =>
                {
                    b.HasOne("CPRG005.Final.Domain.Entities.Dock", "Dock")
                        .WithMany()
                        .HasForeignKey("DockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dock");
                });
#pragma warning restore 612, 618
        }
    }
}
